<a href="https://colab.research.google.com/github/matteasu/ML-exercises/blob/main/lecture1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Exercise 1

- Crete an ndarray x of shape = (5,4) with random numbers
  - each of the 5 rows represents a sample with 4 features
- Create a flat ndarray y of shape = (5,) whose elements are 0 and 1
  - each element is the class of the corresponding sample in x

**Hint**:

    use np.random.rand() and np.random.randint

In [8]:
import numpy as np
x_rows = 5
x_cols = 4
y_cols = 1
start = 0
end = 2
x = np.random.rand(x_rows,x_cols)
y = np.random.randint(start,end,[x_rows,])
#or with rand randm(size) > 0.5


## Exercise 2
- Define a function `extract_subset(x, y, y0)` that takes as input:
  - the feature matrix x, and the labels y from the previous exercise
  - a target class y0 (i.e either y0=0 or y0=1)
- and returns a feature matrix containing only samples belonging to y0

**Hint**

    use array indexing with y==y0

In [11]:
def extract_subset(x,y,y0=0):
  return x[y==y0,:]

[[0.51445358 0.63940065 0.19946504 0.94573375]
 [0.03416667 0.27149433 0.04869924 0.97903118]
 [0.73919549 0.38672063 0.52330456 0.46165871]]


## Exercise 3
- define a function `min_feature_values(x)` that returns the minimum value of each feature in x
- apply it on the previously extracted samples x0 of class 0

**Hint**

    use np.min with a proper axis value

With axis value 1 it gives the minimum across different columns
With axis value 0 it gives the minimum across different rows

In [17]:
def min_feature_values(x):
  return np.min(x,axis=0)

print(min_feature_values(extract_subset(x,y,0)))

[0.03416667 0.27149433 0.04869924 0.46165871]
