<a href="https://colab.research.google.com/github/matteasu/ML-exercises/blob/main/lecture1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Exercise 1

- Crete an ndarray x of shape = (5,4) with random numbers
  - each of the 5 rows represents a sample with 4 features
- Create a flat ndarray y of shape = (5,) whose elements are 0 and 1
  - each element is the class of the corresponding sample in x

**Hint**:

    use np.random.rand() and np.random.randint

In [22]:
import numpy as np
x_rows = 5
x_cols = 4
y_cols = 1
start = 0
end = 2
x = np.random.rand(x_rows,x_cols)
y = np.random.randint(start,end,[x_rows,])
#or with rand randm(size) > 0.5
print("x")
print(x)
print("y")
print(y)

x
[[0.54591904 0.9141933  0.74013096 0.59567374]
 [0.73955956 0.32928107 0.59816598 0.26536125]
 [0.82049662 0.35175629 0.10669475 0.77500206]
 [0.93341268 0.8836477  0.65690892 0.41001517]
 [0.32608268 0.05977031 0.34172637 0.21661125]]
y
[0 1 1 0 0]


## Exercise 2
- Define a function `extract_subset(x, y, y0)` that takes as input:
  - the feature matrix x, and the labels y from the previous exercise
  - a target class y0 (i.e either y0=0 or y0=1)
- and returns a feature matrix containing only samples belonging to y0

**Hint**

    use array indexing with y==y0

In [23]:
def extract_subset(x,y,y0=0):
  return x[y==y0,:]

print(extract_subset(x,y,0))

[[0.54591904 0.9141933  0.74013096 0.59567374]
 [0.93341268 0.8836477  0.65690892 0.41001517]
 [0.32608268 0.05977031 0.34172637 0.21661125]]


## Exercise 3
- define a function `min_feature_values(x)` that returns the minimum value of each feature in x
- apply it on the previously extracted samples x0 of class 0

**Hint**

    use np.min with a proper axis value

With axis value 1 it gives the minimum across different columns
With axis value 0 it gives the minimum across different rows

In [24]:
def min_feature_values(x):
  return np.min(x,axis=0)

print(min_feature_values(extract_subset(x,y,0)))

[0.32608268 0.05977031 0.34172637 0.21661125]


## Exercise 4
- define a function `make_gaussian_dataset(n0, n1, mu0, mu1)` that generates a two-class gaussian dataset in a bi-dimensional space
- n0, n1 are the number of samples for class 0 and class 1
- mu0, mu1 are the mean of the two Gaussians (one per class)

We consider only Gaussian distributions with covariance equal to the identity matrix here for simplyicity 
- The function returns the corresponding feature matrix and labels x,y

**Hint**
- use np.random.randn() to generate random numbers from a standard gaussian distribution, with zero mean and unit variance, then transform them to have a different mean (x2 per class)
- use np.ones and/or np.zeros for class labels
- use vstack or hstack to concatenate arrays





In [26]:
n0 = 10
n1 = 10
#the means have to be a vector since i'm in a bidimensional space
mu0 = [0, 0]
mu1 = [5, 5]
def make_gaussian_dataset(n0, n1, mu0, mu1):
  # cast the lists to arrays
  mu0 = np.array(mu0)
  mu1 = np.array(mu1)
  # generating samples
  n_features = mu0.shape[0]
  # we add the mean to obbtain the wanted mean
  x0 = np.random.randn(n0, n_features) + mu0 #python broadcasting
  y0 = np.zeros(shape=[n0,]) #class labels
  x1 = np.random.randn(n1, n_features) + mu1
  y1 = np.ones(shape=[n0,])

  #concatenate data and labels

  x = np.vstack((x0,x1))
  y = np.hstack((y0,y1))
  return x,y

  #from matplotlib import pyplot as plt
  #plt.plot(x0[:,0],x0[:,1],'.') #plotting the first and second column
  #plt.show()


xn,yn = make_gaussian_dataset(10,10,[-1,-1],[+1,+1])
print('xn:\n',xn)
print('yn:\n',yn) 

xn:
 [[-0.31920297 -1.12432698]
 [-0.44221873 -0.27261646]
 [-0.11681923 -0.92694944]
 [ 0.61675415 -1.477455  ]
 [-1.84590937 -1.52979504]
 [ 0.39326852 -0.24459244]
 [-0.76806789 -0.71785062]
 [-0.85633547 -0.27215762]
 [-1.63260969  0.29697721]
 [-2.18330009 -3.71731781]
 [ 1.34758826  1.28740794]
 [ 2.58090716  0.23089906]
 [ 1.24332202  2.60318469]
 [-0.00994825  0.62532443]
 [ 1.84181811  0.29187226]
 [ 0.79736333  0.01961835]
 [-0.30965741  1.88794142]
 [-0.23532419  1.49748763]
 [-0.34917881  0.33458628]
 [ 0.44399991 -0.32066401]]
yn:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
